### ISSUE TITLE
Different colour/image to selected and not selected ticks

### ISSUE THREAD

**Issue by kosciukus** [SwiftArchitect/TGPControls#26]
Hello SwiftArchitect Team!
First off all thank you very much for this awesome plugin! It helped me a lot :)
I have one question/issue. Is there a way to assign different image/colour to ticks on the left of thumb and ticks on the right?

Thanks!

**Comment by SwiftArchitect** [comment]
Hey thanks for the heads up. Somehow this issue eluded my attention.
Assigned to self today.

**Comment by SwiftArchitect** [comment]
As it turns out, the current track and tick layout is done in a single layer using a bezier, and it would probably be easier to add a gradient rather than changing the ticks dynamically. The same is not quite true with tick images, but these, just like the programmatically drawn ticks, have no real concept of a selection.

IT may be difficult to keep the product efficient (I rely on CALayers for all animations) and not drift too far from all the rendering code provided for free by the OS.

Suggestions welcome.

**Comment by adarshurs** [comment]
Hello,

Thank you for the library, it's awsome.

Is there any way to change (all) ticks color of discrete slider? so far I couldn't find any way to do that, it's the only issue preventing me from adding this library to my app.

**Comment by SwiftArchitect** [comment]
Can you invite me to a chat via Skype or Google Hangout?
Cheers,
Xavier

**Comment by adarshurs** [comment]
Invited you on hangout, check your inbox.

Thanks

**Comment by felixsolorzano** [comment]
Any updates on this?

**Comment by SwiftArchitect** [comment]
Working on it today!

X.

**Comment by felixsolorzano** [comment]
@SwiftArchitect Hi, I noticed you released v5.0.2, but I don't find the way to set the color of the ticks on the left to a different color from the ones on the right of the thumb, could you help me with this?

**Comment by SwiftArchitect** [comment]
Correct.

**Comment by SwiftArchitect** [comment]
Addressed in 5.1.0: API change.
